branch-defaults:
  test-aws:
    environment: null
  test-aws-development:
    environment: rcpw-env
    group_suffix: null
environment-defaults:
  rcpw-env:
    branch: null
    repository: null
global:
  application_name: rcpw
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: rcpw
  repository: null
  sc: git
  workspace_type: Application
